pipeline {
    agent any

    stages {

        stage('Checkout'){
            steps{
                git url: 'https://github.com/tharukadilshani/kodekloud-jenkins-project1', branch: 'main'
                sh "ls -ltr"
            }
        }


        stage('Setup') {
            steps {
           
               sh "pip3 install -r requirements.txt"
            
            }
        }
        stage('Test') {
            steps {
                sh "pytest"
                
            }
        }    
        stage('Deployment') {
            input {
                message "Do you want to proceed further?"
                ok "Yes"
            }
            steps {
                echo "Running Deployment"
                
            }
        } 
        
            
    }
}