pipeline {
    agent any

    stages {

        stage('Checkout'){
            steps{
                git url: 'https://github.com/tharukadilshani/kodekloud-jenkins-project1', branch: 'main'
                sh "ls -ltr"
            }
        }


        
            
    }
}